from django.urls import path
from django.views.generic import TemplateView
from . import views
from . import views_admin

urlpatterns = [
    path('robots.txt', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    path('', views.index, name='index'),
    path('search/', views.search_products, name='search_products'),
    path('products/', views.product_list, name='product_list'),
    path('product/<slug:slug>/', views.product_detail, name='product_detail'),
    path('categories/', views.category_list, name='category_list'),
    path('category/<slug:slug>/', views.category_detail, name='category_detail'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('cart/', views.cart_detail, name='cart_detail'),
    path('cart/add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('cart/remove/<int:item_id>/', views.cart_remove, name='cart_remove'),
    path('cart/update/<int:item_id>/', views.cart_update, name='cart_update'),
    path('checkout/', views.checkout, name='checkout'),
    path('order/success/<int:order_id>/', views.order_success, name='order_success'),
    path('orders/', views.order_history, name='order_history'),
    path('order/<int:order_id>/', views.order_detail, name='order_detail'),
    path('dashboard/', views_admin.dashboard, name='dashboard'),
    path('dashboard/products/', views_admin.product_list, name='admin_product_list'),
    path('dashboard/products/create/', views_admin.product_create, name='admin_product_create'),
    path('dashboard/products/update/<int:product_id>/', views_admin.product_update, name='admin_product_update'),
    path('dashboard/products/delete/<int:product_id>/', views_admin.product_delete, name='admin_product_delete'),
    path('dashboard/categories/', views_admin.category_list, name='admin_category_list'),
    path('dashboard/categories/create/', views_admin.category_create, name='admin_category_create'),
    path('dashboard/categories/update/<int:category_id>/', views_admin.category_update, name='admin_category_update'),
    path('dashboard/categories/delete/<int:category_id>/', views_admin.category_delete, name='admin_category_delete'),
    path('dashboard/orders/', views_admin.order_list, name='admin_order_list'),
    path('dashboard/orders/<int:order_id>/', views_admin.order_detail, name='admin_order_detail'),
    path('dashboard/orders/delete/<int:order_id>/', views_admin.order_delete, name='admin_order_delete'),
    path('dashboard/users/', views_admin.user_list, name='admin_user_list'),
    path('dashboard/users/toggle-staff/<int:user_id>/', views_admin.user_toggle_staff, name='admin_user_toggle_staff'),
    path('dashboard/users/delete/<int:user_id>/', views_admin.user_delete, name='admin_user_delete'),
]
